# Generated by Django 4.2.5 on 2025-07-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="密码")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后登录"
                    ),
                ),
                ("usercode", models.CharField(max_length=120, verbose_name="用户编码")),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "学生"), (2, "教师"), (3, "管理员")],
                        default=1,
                        verbose_name="角色",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="真实姓名"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "男"), ("F", "女")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "自定义用户",
                "verbose_name_plural": "自定义用户",
                "db_table": "own_models_custom_user",
            },
        ),
    ]
