# Generated by Django 4.2.23 on 2025-07-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("own_models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="题目标题")),
                ("description", models.TextField(verbose_name="题目描述")),
                (
                    "input_description",
                    models.TextField(blank=True, verbose_name="输入描述"),
                ),
                (
                    "output_description",
                    models.TextField(blank=True, verbose_name="输出描述"),
                ),
                ("sample_input", models.TextField(blank=True, verbose_name="样例输入")),
                (
                    "sample_output",
                    models.TextField(blank=True, verbose_name="样例输出"),
                ),
                ("hint", models.TextField(blank=True, null=True, verbose_name="提示")),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "简单"), (2, "中等"), (3, "困难")],
                        default=1,
                        verbose_name="难度",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "submission_count",
                    models.IntegerField(default=0, verbose_name="提交次数"),
                ),
                (
                    "accepted_count",
                    models.IntegerField(default=0, verbose_name="通过次数"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_problems",
                        to="own_models.customuser",
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目",
                "verbose_name_plural": "题目",
                "db_table": "own_models_problem",
            },
        ),
    ]
