# Generated by Django 4.2.23 on 2025-07-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("own_models", "0002_problem"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="problem_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "选择题"),
                    (2, "填空题"),
                    (3, "判断题"),
                    (4, "编程题"),
                    (5, "简答题"),
                ],
                default=1,
                verbose_name="题目类型",
            ),
        ),
    ]
