# Generated by Django 4.2.23 on 2025-07-29 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("own_models", "0003_problem_problem_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(verbose_name="代码")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                            ("c", "C"),
                            ("javascript", "JavaScript"),
                        ],
                        max_length=20,
                        verbose_name="编程语言",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "评测中"),
                            ("accepted", "通过"),
                            ("wrong_answer", "答案错误"),
                            ("time_limit_exceeded", "超时"),
                            ("memory_limit_exceeded", "内存超限"),
                            ("runtime_error", "运行时错误"),
                            ("compile_error", "编译错误"),
                            ("system_error", "系统错误"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="状态",
                    ),
                ),
                (
                    "execution_time",
                    models.IntegerField(default=0, verbose_name="执行时间(ms)"),
                ),
                (
                    "memory_used",
                    models.IntegerField(default=0, verbose_name="内存使用(KB)"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="own_models.problem",
                        verbose_name="题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="own_models.customuser",
                        verbose_name="提交用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "提交记录",
                "verbose_name_plural": "提交记录",
                "db_table": "own_models_submission",
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField(verbose_name="输入数据")),
                ("expected_output", models.TextField(verbose_name="期望输出")),
                (
                    "is_sample",
                    models.BooleanField(default=False, verbose_name="是否为样例"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="own_models.problem",
                        verbose_name="题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例",
                "verbose_name_plural": "测试用例",
                "db_table": "own_models_testcase",
            },
        ),
        migrations.CreateModel(
            name="TestCaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("passed", "通过"), ("failed", "失败")],
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "execution_time",
                    models.IntegerField(default=0, verbose_name="执行时间(ms)"),
                ),
                (
                    "memory_used",
                    models.IntegerField(default=0, verbose_name="内存使用(KB)"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="own_models.submission",
                        verbose_name="提交记录",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="own_models.testcase",
                        verbose_name="测试用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例结果",
                "verbose_name_plural": "测试用例结果",
                "db_table": "own_models_testcase_result",
            },
        ),
        migrations.CreateModel(
            name="StudentStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_submissions",
                    models.IntegerField(default=0, verbose_name="总提交次数"),
                ),
                (
                    "accepted_submissions",
                    models.IntegerField(default=0, verbose_name="通过提交次数"),
                ),
                (
                    "total_problems_attempted",
                    models.IntegerField(default=0, verbose_name="尝试题目数"),
                ),
                (
                    "total_problems_solved",
                    models.IntegerField(default=0, verbose_name="解决题目数"),
                ),
                (
                    "easy_problems_solved",
                    models.IntegerField(default=0, verbose_name="简单题解决数"),
                ),
                (
                    "medium_problems_solved",
                    models.IntegerField(default=0, verbose_name="中等题解决数"),
                ),
                (
                    "hard_problems_solved",
                    models.IntegerField(default=0, verbose_name="困难题解决数"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="own_models.customuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生统计",
                "verbose_name_plural": "学生统计",
                "db_table": "own_models_student_statistics",
            },
        ),
    ]
