# Generated by Django 4.2.23 on 2025-07-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("own_models", "0004_submission_testcase_testcaseresult_studentstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="knowledge_point",
            field=models.CharField(
                blank=True,
                help_text="例如：判断、循环、函数、模块等",
                max_length=100,
                null=True,
                verbose_name="知识点",
            ),
        ),
    ]
