# Generated by Django 4.2.23 on 2025-08-03 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("own_models", "0005_problem_knowledge_point"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="标签名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="标签描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
                "db_table": "own_models_tag",
            },
        ),
        migrations.CreateModel(
            name="RankingSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problems_completed",
                    models.IntegerField(default=0, verbose_name="Problems Completed"),
                ),
                (
                    "total_attempts",
                    models.IntegerField(default=0, verbose_name="Total Attempts"),
                ),
                (
                    "rank_position",
                    models.IntegerField(default=0, verbose_name="Rank Position"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking",
                        to="own_models.customuser",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ranking System",
                "verbose_name_plural": "Ranking Systems",
                "db_table": "own_models_ranking_system",
            },
        ),
        migrations.AddField(
            model_name="problem",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="problems",
                to="own_models.tag",
                verbose_name="标签",
            ),
        ),
    ]
