# Generated by Django 4.2.23 on 2025-08-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("own_models", "0006_tag_rankingsystem_problem_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strengths",
                    models.TextField(
                        blank=True,
                        help_text="Knowledge points the student is strong in",
                        verbose_name="Strengths",
                    ),
                ),
                (
                    "weaknesses",
                    models.TextField(
                        blank=True,
                        help_text="Knowledge points the student needs to improve",
                        verbose_name="Weaknesses",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Recommended problems or topics to practice",
                        verbose_name="Recommendations",
                    ),
                ),
                (
                    "average_completion_time",
                    models.FloatField(
                        default=0, verbose_name="Average Completion Time (ms)"
                    ),
                ),
                (
                    "success_rate",
                    models.FloatField(default=0, verbose_name="Success Rate (%)"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_feedback",
                        to="own_models.customuser",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Feedback",
                "verbose_name_plural": "Learning Feedbacks",
                "db_table": "own_models_learning_feedback",
            },
        ),
        migrations.CreateModel(
            name="KnowledgePointPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "knowledge_point",
                    models.CharField(max_length=100, verbose_name="Knowledge Point"),
                ),
                (
                    "problems_attempted",
                    models.IntegerField(default=0, verbose_name="Problems Attempted"),
                ),
                (
                    "problems_solved",
                    models.IntegerField(default=0, verbose_name="Problems Solved"),
                ),
                (
                    "average_attempts",
                    models.FloatField(
                        default=0, verbose_name="Average Attempts per Problem"
                    ),
                ),
                (
                    "average_time",
                    models.FloatField(default=0, verbose_name="Average Time (ms)"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_performances",
                        to="own_models.customuser",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Point Performance",
                "verbose_name_plural": "Knowledge Point Performances",
                "db_table": "own_models_knowledge_point_performance",
                "unique_together": {("user", "knowledge_point")},
            },
        ),
    ]
