# Generated by Django 5.1.6 on 2025-08-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("own_models", "0007_learningfeedback_knowledgepointperformance"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="是否职员"),
        ),
    ]
